global:
  domain: fct-abuja-hcm.digit.org

disableAnnotationTimestamp: true

transformer:
  namespace: "abuja"
  image:
    repository: egovio/transformer
    tag: HDDF-5226-1403ae9
  heap: "-Xmx1536m -Xms1536m"
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  cpu_requests: 300m
  memory_requests: 1.75Gi
  cpu_limits: 400m
  memory_limits: 2.25Gi
  java-enable-debug: true
  save-project-task-topic: "ab-save-project-task-topic"
  update-project-task-topic: "ab-update-project-task-topic"
  transformer-producer-bulk-project-task-index-v1-topic: "ab-transformer-producer-bulk-project-task-index-v1-topic"
  save-project-staff-topic: "ab-save-project-staff-topic"
  update-project-staff-topic: "ab-update-project-staff-topic"
  transformer-producer-bulk-project-staff-index-v1-topic: "ab-transformer-producer-bulk-project-staff-index-v1-topic"
  transformer-producer-bulk-project-index-v1-topic: "ab-transformer-producer-bulk-project-index-v1-topic"
  save-project: "ab-save-project"
  update-project: "ab-update-project"
  save-household-member-topic: "ab-save-household-member-topic"
  transformer-producer-household-member-index-v1-topic: "ab-transformer-producer-household-member-index-v1-topic"
  save-household-topic: "ab-save-household-topic"
  update-household-topic: "ab-update-household-topic"
  transformer-producer-household-index-v1-topic: "ab-transformer-producer-household-index-v1-topic"
  transformer-producer-service-index-v2-topic: "ab-transformer-producer-service-index-v2-topic"
  save-stock-topic: "ab-save-stock-topic"
  update-stock-topic: "ab-update-stock-topic"
  transformer-producer-bulk-stock-index-v1-topic: "ab-transformer-producer-bulk-stock-index-v1-topic"
  transformer-producer-bulk-stock-index-updated-v1-topic: "ab-transformer-producer-bulk-stock-index-updated-v1-topic"
  save-facility-topic: "ab-save-facility-topic"
  update-facility-topic: "ab-update-facility-topic"
  save-service: "ab-save-service"
  transformer-producer-service-request-index-v1-topic: "ab-transformer-producer-service-request-index-v1-topic"
  save-referral-topic: "ab-save-referral-topic"
  transformer-producer-referral-index-v1-topic: "ab-transformer-producer-referral-index-v1-topic"
  update-referral-topic: "ab-update-referral-topic"
  save-side-effect-topic: "ab-save-side-effect-topic"
  update-side-effect-topic: "ab-update-side-effect-topic"
  transformer-producer-side-effect-index-v1-topic: "ab-transformer-producer-side-effect-index-v1-topic"
  save-pgr-request: "ab-save-pgr-request"
  transformer-save-pgr-request: "ab-transformer-save-pgr-request"
  update-pgr-request: "ab-update-pgr-request"
  save-hfreferral-topic: "ab-save-hfreferral-topic"
  update-hfreferral-topic: "ab-update-hfreferral-topic"
  transformer-producer-hfreferral-index-v1-topic: "ab-transformer-producer-hfreferral-index-v1-topic"
  transformer-producer-hfreferral-service-index-topic: "ab-transformer-producer-hfreferral-service-index-topic"
  transformer-producer-finance-checklist-index-v1-topic: "ab-transformer-producer-finance-checklist-index-v1-topic"
  transformer-producer-special-spraying-index-topic: "ab-transformer-producer-special-spraying-index-topic"
  save-attendance-log: "ab-save-attendance-log"
  update-attendance-log: "ab-update-attendance-log"
  transformer-save-attendance-log: "ab-transformer-save-attendance-log"
  transformer-save-attendance-register: "ab-transformer-save-attendance-register"
  transformer-save-attendance-staff: "ab-save-staff"
  transformer-update-attendance-staff: "ab-update-staff"
  transformer-save-attendance-attendee: "ab-save-attendee"
  transformer-update-attendance-attendee: "ab-update-attendee"
  transformer-producer-attendance-staff-index: "ab-transformer-producer-attendance-staff-index"
  transformer-producer-attendee-index: "ab-transformer-producer-attendee-index"
  transformer-producer-extra-transformed-checklist-index-topic: "ab-transformer-producer-extra-transformed-checklist-index-topic"
  update-household-member-topic: "ab-update-household-member-topic"
  save-stock-reconciliation-topic: "ab-save-stock-reconciliation-topic"
  update-stock-reconciliation-topic: "ab-update-stock-reconciliation-topic"
  transformer-producer-stock-recon-index-v1-topic: "ab-transformer-producer-stock-recon-index-v1-topic"
  health-transformer: "ab-health-transformer"
  transformer-consumer-error-tracer-topic: "error-details-indexer-topic"
  transformer-producer-error-details-index-v1-topic: "ab-transformed-errors-topic"
  transformer-error-skip-error-messages: "UPLOAD_ERROR_FROM_APP"
  transformer-error-skip-error-codes: "DUPLICATE_ENTITY,INDIVIDUAL_ALREADY_MEMBER_OF_HOUSEHOLD,HOUSEHOLD_ALREADY_HAS_HEAD"
  transformer-error-skip-url-contains: "facility,resource"
  state-level-tenantid: "ab"
  expense-bill-create-health-topic: "ab-expense-bill-create-health"
  expense-bill-update-health-topic: "ab-expense-bill-update-health"
  transformer-bill-index-topic: "ab-transformer-bill-index-topic"
  transformer-billdetail-index-topic: "ab-transformer-billdetail-index-topic"
  expense-bill-report-save-topic: "ab-expense-bill-report-save"
  expense-bill-report-update-topic: "ab-expense-bill-report-update"
  transformer-billreport-index-topic: "ab-transformer-billreport-index-topic"
  save-musterroll-health-topic: "ab-save-musterroll-health"
  update-musterroll-health-topic: "ab-update-musterroll-health"
  transformer-producer-muster-roll-index-v1-topic: "ab-transformer-producer-muster-roll-index-v1-topic"
  expense-bill-detail-create-topic: "ab-expense-bill-detail-create"
  expense-bill-detail-update-topic: "ab-expense-bill-detail-update"
  egov_localization_locale_code: "en_NG"
  egov-localization-module-name: "hcm-boundary-admin"
  transformer-consumer-create-user-action-topic: "ab-save-user-action-project-task-topic"
  transformer-consumer-update-user-action-topic: "ab-update-user-action-project-task-topic"
  transformer-producer-user-action-index-v1-topic: "ab-transformer-producer-user-action-index-v1-topic"

hcm-moz-impl:
  namespace: abuja
  replicas: 1
  heap: "-Xmx2048m -Xms2048m"
  memory_limits: "2Gi"
  startDate: "13/06/2025"
  endDate: "17/06/2025"
  boundary-code: "ab"
  create-boundaryCSV-data: "ab-create-boundaryCSV-data"
  update-dhis2-job: "ab-update-dhis2-job"
  create-dhis2-job: "ab-create-dhis2-job"
  create-boundary-data: "ab-create-boundary-data"
  update-digit-dhis2-mapping: "ab-update-digit-dhis2-mapping"
  create-digit-dhis2-mapping: "ab-create-digit-dhis2-mapping"
  update-digit-record: "ab-update-digit-record"
  create-digit-record: "ab-create-digit-record"
  update-dhis2-digit-mapping: "ab-update-dhis2-digit-mapping"
  create-dhis2-digit-mapping: "ab-create-dhis2-digit-mapping"
  update-dhis2-record: "ab-update-dhis2-record"
  create-dhis2-record: "ab-create-dhis2-record"
  resources:
    requests:
      memory: "3Gi"
    limits:
      memory: "3Gi"


digit-ui:
  namespace: abuja
  image:
    repository: egovio/digit-ui
    tag: impel-central-instance-nigeria-multiarch-new-f9b9f6fb

  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfig-ab.js type=text/javascript></script>
      ';"

payments-ui:
  namespace: abuja
  image:
    repository: egovio/payments-ui
    tag: HDDF-4931-151549b
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfigPayments-ab.js type=text/javascript></script>
      ';"

workbench-ui:
  namespace: abuja
  image:
    repository: egovio/workbench-ui
    tag: nigeria_mc-5212cd5
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfigWorkbench-ab.js type=text/javascript></script>
      ';"

dashboard-ui:
  namespace: abuja
  image:
    repository: egovio/dashboard-ui
    tag: HDDF-4931-a645e10
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfigDashboard-ab.js type=text/javascript></script>
      ';"
