cluster-configs:
    secrets:
        db:
            namespace:
                - ENC[AES256_GCM,data:NKOxETXlYyuj,iv:KlgVQly4rgBS8yOD5tEf2k1QpvvFmjTqjJYg8x8OLsU=,tag:1meL1fxpW9hNnm0ne12euw==,type:str]
            username: ENC[AES256_GCM,data:flruwJt6aE65OoxN,iv:hSgQ/bTfiFpuuRQlvK/NptMUj7LW+AaMNc5xGJ7SMgc=,tag:sIov/QuviVao7Mbqmq+MSA==,type:str]
            password: ENC[AES256_GCM,data:3JRBJRze0fLLcSAJiqQS,iv:pXGobxwuzCfn6Qe5CquIWPtIcylS8rMzyeEp+ytSCEk=,tag:sv/9Did3JvLb7XOSRulfow==,type:str]
            flywayUsername: ENC[AES256_GCM,data:AwdOZooFkGE752vu,iv:5aM/Tcnp/mVgCpk5WfijfOwlPGplpr+IYUeuJqPYM6w=,tag:YQZAyScLks6CIYB5bcfQYg==,type:str]
            flywayPassword: ENC[AES256_GCM,data:O/1690f7ImR1k9ZB7mwz,iv:HnHdrDXzrUD1cbmBGMtV/4H29btxCn1XDqGehj/7GT4=,tag:9UqAUIFgp1v997Rq0ZN4aw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:022499048165:key/e88e5bd9-8616-40c1-9863-674dc9132cd2
          created_at: "2026-05-02T10:39:07Z"
          enc: AQICAHhJ0PDePol2tB09qxy9aLfmveTaYaEmWqZ2FTC4BsxbAQFzz7m4TTcJElO/ub2wOTvMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1EIreiUnc0GmuNa+AgEQgDtWTjAEgdnhKCXV0vFD5APA5QbLT2msROAfruDN2Mnivp10QcWZ+fJ69aOKYwV6bxA3aSJ80s5/Lwm6SQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-02T10:39:08Z"
    mac: ENC[AES256_GCM,data:5b8WxQBrsxR/v+ozdR0ewa52Lcr0kkje14YAuMD7XKN3FbKLF/5aEqu1hRdzkj3rpCaUkZUFDqACkESnE+fNFxa87HpShaQ4vNEm/vxgCRN3CvohqSkRwVjG1KdaMyvpMeLFSSaM+1rjogDD+M3mSca0IITG8l59xafMvyZLO3c=,iv:68DQjzzt+86BWK3Bp2+ECTY0fI9XptmAkTEVhP4y9Cw=,tag:aMLuAzMe6bDpouwC1dozzQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
