global:
  domain: jigawa-central-hcm.digit.org

service:
  additionalAnnotations: |
    zuul/route-host: jigawa-central-hcm.digit.org

cluster-configs:
  namespaces:
    create: true
    values: [ jigawa ]

  configmaps:
    egov-config:
      namespace: [ jigawa ]
      data:
        db-host: "ng-central-prd-db.cpe4q0cycqi7.af-south-1.rds.amazonaws.com" ## Add db-host name eg: egov-demo.database.azure.com
        db-name: "ngcentralprd" ## Add db-name
        db-url: "jdbc:postgresql://ng-central-prd-db.cpe4q0cycqi7.af-south-1.rds.amazonaws.com:5432/ngcentralprd"
        db-read-url: "jdbc:postgresql://ng-central-prd-read-db.cpe4q0cycqi7.af-south-1.rds.amazonaws.com:5432/ngcentralprd"
        kd-db-url: "jdbc:postgresql://ng-central-prd-db.cpe4q0cycqi7.af-south-1.rds.amazonaws.com:5432/ngcentralprd?currentSchema=kd"
        jg-db-url: "jdbc:postgresql://ng-central-prd-db.cpe4q0cycqi7.af-south-1.rds.amazonaws.com:5432/ngcentralprd?currentSchema=jg"
        kb-db-url: "jdbc:postgresql://ng-central-prd-db.cpe4q0cycqi7.af-south-1.rds.amazonaws.com:5432/ngcentralprd?currentSchema=kb"
        domain: "jigawa-central-hcm.digit.org" ## Add your Domain Name
        redis-host: "redis.backbone"
        redis-downsync-host: "ng-central-redis.nolaw2.ng.0001.afs1.cache.amazonaws.com"
        egov-services-fqdn-name: "https://jigawa-central-hcm.digit.org/" ## Add your Domain Name
        state-level-tenantid-length: "1"
        state-schema-index-position-tenantid: "0"
        is-environment-central-instance: "false"
        aws-cluster-ip: "https://AD11FA377F3AEE4369833D9626BD7A83.gr7.af-south-1.eks.amazonaws.com"
        aws-region: "af-south-1"
        aws-cluster-name: "arn:aws:iam::022499048165:role/ng-central-prd-cluster-20250509110729607700000001"
        egov-state-level-tenant-id: "jg"
        state-level-tenant-id: "jg"
        s3-assets-bucket: "(central-instance-assets)"
        es-host: "elasticsearch-data.es-cluster-v8"
        es-indexer-host: "https://elasticsearch-data.es-cluster-v8:9200/"
        flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/qa"
        kafka-brokers: "b-1.centralmsk.6jj53l.c2.kafka.af-south-1.amazonaws.com:9092,b-2.centralmsk.6jj53l.c2.kafka.af-south-1.amazonaws.com:9092,b-3.centralmsk.6jj53l.c2.kafka.af-south-1.amazonaws.com:9092"
        kafka-infra-brokers: "release-name-kafka-controller-headless.kafka-cluster:9092"
        logging-level-jdbc: "DEBUG"
        mobile-validation-workaround: "true"
        serializers-timezone-in-ist: "true"
        server-tomcat-max-connections: "500"
        server-tomcat-max-threads: "10"
        sms-enabled: "true"
        spring-datasource-tomcat-initialSize: "1"
        spring-datasource-tomcat-max-active: "2"
        spring-jpa-show-sql: "true"
        timezone: "UTC"
        tracer-errors-provideexceptionindetails: "true"
        egov-env: "PROD"
        boundary-hierarchy: "ADMIN"
        egov-internal-microservice-user-uuid: "e1f57dfe-35a0-494a-911d-22cd3f786612"
        host-map: "{'kd':'https://kaduna-central-hcm.digit.org/','jg':'https://jigawa-central-hcm.digit.org/','kb':'https://kebbi-azm-central-hcm.digit.org/'}"
        db-schema-names: "jg"

egov-enc-service:
  secret-name: "egov-enc-service"
  namespace: "jigawa"
  heap: "-Xmx512m -Xms512m"
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  ingress:
    enabled: false
    zuul: false
  cpu_requests: 100m
  memory_requests: 768Mi
  cpu_limits: 200m
  memory_limits: 1Gi

individual:
  initContainers:
    dbMigration:
      enabled: false
  ingress:
    enabled: false
    zuul: false
  namespace: "jigawa"
  central-instance-build: true
  heap: "-Xmx768m -Xms512m"
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  cpu_requests: 300m
  memory_requests: 768Mi
  cpu_limits: 400m
  memory_limits: 1Gi

transformer:
  image:
    repository: egovio/transformer
    tag: HDDF-5226-28d86d4
  namespace: "jigawa"
  heap: "-Xmx1536m -Xms1536m"
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  ingress:
    enabled: false
    zuul: false
  cpu_requests: 300m
  memory_requests: 1.75Gi
  cpu_limits: 400m
  memory_limits: 2.25Gi
  java-enable-debug: true
  save-project-task-topic: "jg-save-project-task-topic"
  update-project-task-topic: "jg-update-project-task-topic"
  transformer-producer-bulk-project-task-index-v1-topic: "jg-transformer-producer-bulk-project-task-index-v1-topic"
  save-project-staff-topic: "jg-save-project-staff-topic"
  update-project-staff-topic: "jg-update-project-staff-topic"
  transformer-producer-bulk-project-staff-index-v1-topic: "jg-transformer-producer-bulk-project-staff-index-v1-topic"
  transformer-producer-bulk-project-index-v1-topic: "jg-transformer-producer-bulk-project-index-v1-topic"
  save-project: "jg-save-project"
  update-project: "jg-update-project"
  save-household-member-topic: "jg-save-household-member-topic"
  transformer-producer-household-member-index-v1-topic: "jg-transformer-producer-household-member-index-v1-topic"
  save-household-topic: "jg-save-household-topic"
  update-household-topic: "jg-update-household-topic"
  transformer-producer-household-index-v1-topic: "jg-transformer-producer-household-index-v1-topic"
  transformer-producer-service-index-v2-topic: "jg-transformer-producer-service-index-v2-topic"
  save-stock-topic: "jg-save-stock-topic"
  update-stock-topic: "jg-update-stock-topic"
  transformer-producer-bulk-stock-index-v1-topic: "jg-transformer-producer-bulk-stock-index-v1-topic"
  transformer-producer-bulk-stock-index-updated-v1-topic: "jg-transformer-producer-bulk-stock-index-updated-v1-topic"
  save-facility-topic: "jg-save-facility-topic"
  update-facility-topic: "jg-update-facility-topic"
  save-service: "jg-save-service"
  transformer-producer-service-request-index-v1-topic: "jg-transformer-producer-service-request-index-v1-topic"
  save-referral-topic: "jg-save-referral-topic"
  transformer-producer-referral-index-v1-topic: "jg-transformer-producer-referral-index-v1-topic"
  update-referral-topic: "jg-update-referral-topic"
  save-side-effect-topic: "jg-save-side-effect-topic"
  update-side-effect-topic: "jg-update-side-effect-topic"
  transformer-producer-side-effect-index-v1-topic: "jg-transformer-producer-side-effect-index-v1-topic"
  save-pgr-request: "jg-save-pgr-request"
  transformer-save-pgr-request: "jg-transformer-save-pgr-request"
  update-pgr-request: "jg-update-pgr-request"
  save-hfreferral-topic: "jg-save-hfreferral-topic"
  update-hfreferral-topic: "jg-update-hfreferral-topic"
  transformer-producer-hfreferral-index-v1-topic: "jg-transformer-producer-hfreferral-index-v1-topic"
  transformer-producer-hfreferral-service-index-topic: "jg-transformer-producer-hfreferral-service-index-topic"
  transformer-producer-finance-checklist-index-v1-topic: "jg-transformer-producer-finance-checklist-index-v1-topic"
  transformer-producer-special-spraying-index-topic: "jg-transformer-producer-special-spraying-index-topic"
  save-attendance-log: "jg-save-attendance-log"
  update-attendance-log: "jg-update-attendance-log"
  transformer-save-attendance-log: "jg-transformer-save-attendance-log"
  transformer-save-attendance-register: "jg-transformer-save-attendance-register"
  transformer-producer-extra-transformed-checklist-index-topic: "jg-transformer-producer-extra-transformed-checklist-index-topic"
  update-household-member-topic: "jg-update-household-member-topic"
  save-stock-reconciliation-topic: "jg-save-stock-reconciliation-topic"
  update-stock-reconciliation-topic: "jg-update-stock-reconciliation-topic"
  transformer-producer-stock-recon-index-v1-topic: "jg-transformer-producer-stock-recon-index-v1-topic"
  health-transformer: "jg-health-transformer"
  state-level-tenantid: "jg"
  expense-bill-create-health-topic: "jg-expense-bill-create-health"
  expense-bill-update-health-topic: "jg-expense-bill-update-health"
  transformer-bill-index-topic: "jg-transformer-bill-index-topic"
  transformer-billdetail-index-topic: "jg-transformer-billdetail-index-topic"
  expense-bill-report-save-topic: "jg-expense-bill-report-save"
  expense-bill-report-update-topic: "jg-expense-bill-report-update"
  transformer-billreport-index-topic: "jg-transformer-billreport-index-topic"
  save-musterroll-health-topic: "jg-save-musterroll-health"
  update-musterroll-health-topic: "jg-update-musterroll-health"
  transformer-producer-muster-roll-index-v1-topic: "jg-transformer-producer-muster-roll-index-v1-topic"
  expense-bill-detail-create-topic: "jg-expense-bill-detail-create"
  expense-bill-detail-update-topic: "jg-expense-bill-detail-update"
  egov_localization_locale_code: "en_NG"
  egov-localization-module-name: "hcm-boundary-admin"
  transformer-consumer-create-user-action-topic: "jg-save-user-action-project-task-topic"
  transformer-consumer-update-user-action-topic: "jg-update-user-action-project-task-topic"
  transformer-producer-user-action-index-v1-topic: "jg-transformer-producer-user-action-index-v1-topic"

hcm-moz-impl:
  namespace: jigawa
  replicas: 1
  heap: "-Xmx2048m -Xms2048m"
  memory_limits: "2Gi"
  startDate: "29/05/2025"
  endDate: "02/06/2025"
  boundary-code: "kd"
  create-boundaryCSV-data: "jg-create-boundaryCSV-data"
  update-dhis2-job: "jg-update-dhis2-job"
  create-dhis2-job: "jg-create-dhis2-job"
  create-boundary-data: "jg-create-boundary-data"
  update-digit-dhis2-mapping: "jg-update-digit-dhis2-mapping"
  create-digit-dhis2-mapping: "jg-create-digit-dhis2-mapping"
  update-digit-record: "jg-update-digit-record"
  create-digit-record: "jg-create-digit-record"
  update-dhis2-digit-mapping: "jg-update-dhis2-digit-mapping"
  create-dhis2-digit-mapping: "jg-create-dhis2-digit-mapping"
  update-dhis2-record: "jg-update-dhis2-record"
  create-dhis2-record: "jg-create-dhis2-record"
  resources:
    requests:
      memory: "3Gi"
    limits:
      memory: "3Gi"


referralmanagement:
  namespace: jigawa
  ingress:
    enabled: true
    zuul: true
    namespace: egov
    name: referralmanagement-jigawa
    context: referralmanagement
  initContainers:
    dbMigration:
      image:
        repository: egovio/referralmanagement-db
        tag: nigeria-go-deep-2-e0dbbd4
  image:
    repository: egovio/referralmanagement
    tag: nigeria-go-deep-2-e0dbbd4
  central-instance-build: true
  downsync-services-enabled: true
  heap: "-Xmx1536m -Xms768m"
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  cpu_requests: 300m
  memory_requests: 1.5Gi
  cpu_limits: 400m
  memory_limits: 2Gi
  egov-enc-service-configmap-key: "egov-enc-service-jigawa"
  referralmanagement-sideeffect-kafka-create-topic: "jg-save-side-effect-topic"
  referralmanagement-sideeffect-kafka-update-topic: "jg-update-side-effect-topic"
  referralmanagement-sideeffect-kafka-delete-topic: "jg-delete-side-effect-topic"
  referralmanagement-sideeffect-consumer-bulk-create-topic: "jg-save-side-effect-bulk-topic"
  referralmanagement-sideeffect-consumer-bulk-update-topic: "jg-update-side-effect-bulk-topic"
  referralmanagement-sideeffect-consumer-bulk-delete-topic: "jg-delete-side-effect-bulk-topic"
  referralmanagement-referral-kafka-create-topic: "jg-save-referral-topic"
  referralmanagement-referral-kafka-update-topic: "jg-update-referral-topic"
  referralmanagement-referral-kafka-delete-topic: "jg-delete-referral-topic"
  referralmanagement-referral-consumer-bulk-create-topic: "jg-save-referral-bulk-topic"
  referralmanagement-referral-consumer-bulk-update-topic: "jg-update-referral-bulk-topic"
  referralmanagement-referral-consumer-bulk-delete-topic: "jg-delete-referral-bulk-topic"
  referralmanagement-hfreferral-kafka-create-topic: "jg-save-hfreferral-topic"
  referralmanagement-hfreferral-kafka-update-topic: "jg-update-hfreferral-topic"
  referralmanagement-hfreferral-kafka-delete-topic: "jg-delete-hfreferral-topic"
  referralmanagement-hfreferral-consumer-bulk-create-topic: "jg-save-hfreferral-bulk-topic"
  referralmanagement-hfreferral-consumer-bulk-update-topic: "jg-update-hfreferral-bulk-topic"
  referralmanagement-hfreferral-consumer-bulk-delete-topic: "jg-delete-hfreferral-bulk-topic"
  kafka-consumer-group-id: "jg-health-referral-management"

digit-ui:
  namespace: jigawa
  image:
    repository: egovio/digit-ui
    tag: impel-central-instance-nigeria-multiarch-new-f9b9f6fb
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfig-jg.js type=text/javascript></script>
      ';"

disableAnnotationTimestamp: true

payments-ui:
  namespace: jigawa
  image:
    repository: egovio/payments-ui
    tag: HDDF-4931-427abb8
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfigPayments-jg.js type=text/javascript></script>
      ';"

workbench-ui:
  namespace: jigawa
  image:
    repository: egovio/workbench-ui
    tag: HDDF-4931-d008fbe
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfigWorkbench-jg.js type=text/javascript></script>
      ';"

dashboard-ui:
  namespace: jigawa
  image:
    repository: egovio/dashboard-ui
    tag: HDDF-4931-61e2862
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfigDashboard-jg.js type=text/javascript></script>
      ';"