cluster-configs:
    secrets:
        db:
            namespace:
                - ENC[AES256_GCM,data:WhIzgHVE8Kzh,iv:d6IkdYm67NvipoHop/4w76rtPYVuR2xoMQoA1nbLJzI=,tag:IIgO+gGAvzxz8wLVMckj9A==,type:str]
            username: ENC[AES256_GCM,data:GHkGaQQulQN93epK,iv:YMmWHazP5KorvzI/vKS+yNhDSmQu3L4MYNXiOy1/id0=,tag:nLcomoBlwIvkO9IeSDZ0Aw==,type:str]
            password: ENC[AES256_GCM,data:m/E4Yx7eF8+C74owAnso,iv:LC+o25phqqSy7TP4VsmeLgQfKCnj3M+9t28J903lG1I=,tag:Hct0YAyGxzcdAjdP4d8vmw==,type:str]
            flywayUsername: ENC[AES256_GCM,data:xQ8OsLmXEXIdzglI,iv:pB0TpKu1JT5wm6RzWc+lALCSo1nXhljIVloAnqS14pM=,tag:ynf6vb7wvMfcI186sza3Xg==,type:str]
            flywayPassword: ENC[AES256_GCM,data:IxZ3bduNfmogfsf53VGz,iv:6FaJKL636V5DME5+75i6Moy2odUxnNytXurrubxNXjo=,tag:T8AHKQkCrchcVeB0yQj8Mw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:022499048165:key/e88e5bd9-8616-40c1-9863-674dc9132cd2
          created_at: "2026-05-05T13:33:47Z"
          enc: AQICAHhJ0PDePol2tB09qxy9aLfmveTaYaEmWqZ2FTC4BsxbAQFZpk3ebgSdnxuETXu8Gz0xAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnqjWSC7qu/mXkAazAgEQgDtZux9lGR4trvtUkeYi2ApGG5Eb9QJU/Lp2ptHvr3BCyKAKtAlM6YDQ7Cn3VUgvVwpgS8C67BNAN7NKpQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-05T13:33:49Z"
    mac: ENC[AES256_GCM,data:jSMEAwiJhEmRVxsnqVnhlcKIYEVnzn+NnoVcY01ExTp0sfBGmZddA5XRo+K1eCeEsnwMJETQxBlYP7Cv848rAkEFjiR9di/ymlMYaYQELX+8Sncf9WI5X68HzCs6gcXsfjWC/D0Zf34CtxuksG+S+/Bxwg5xyTLnqQYkO1uDcxU=,iv:PVzDhsyz0pmtb9Bf6RktJ7RvjTBRkmT7GULXFXXtVsc=,tag:joUa7xE5t+KL+YhzdrseCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
