global:
  domain: nasarawa-hcm.digit.org
  tracing-enabled: false
# egov-localization:
#   namespace: "oyo"
#   heap: "-Xmx512m -Xms512m"
#   memory_limits: "512Mi"
#   resources:
#     requests:
#       memory: "512Mi"
#     limits:
#       memory: "512Mi"


# boundary-service:
#   namespace: "oyo"
#   heap: "-Xmx512m -Xms512m"
#   memory_limits: "512Mi"
#   resources:
#     requests:
#       memory: "512Mi"
#     limits:
#       memory: "512Mi"

# egov-idgen:
#   namespace: "oyo"
#   heap: "-Xmx512m -Xms512m"
#   memory_limits: "512Mi"
#   resources:
#     requests:
#       memory: "512Mi"
#     limits:
#       memory: "512Mi"

# egov-enc-service:
#   namespace: "oyo"
#   heap: "-Xmx512m -Xms512m"
#   memory_limits: "512Mi"
#   resources:
#     requests:
#       memory: "512Mi"
#     limits:
#       memory: "512Mi"


disableAnnotationTimestamp: true

transformer:
  namespace: "nasarawa"
  image:
    repository: egovio/transformer
    tag: HDDF-5226-5f0424b
  replicas: 2
  heap: "-Xmx1536m -Xms1536m"
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  cpu_requests: 300m
  memory_requests: 1.75Gi
  cpu_limits: 400m
  memory_limits: 2.25Gi
  save-project-task-topic: "na-save-project-task-topic"
  update-project-task-topic: "na-update-project-task-topic"
  transformer-producer-bulk-project-task-index-v1-topic: "na-transformer-producer-bulk-project-task-index-v1-topic"
  save-project-staff-topic: "na-save-project-staff-topic"
  update-project-staff-topic: "na-update-project-staff-topic"
  transformer-producer-bulk-project-staff-index-v1-topic: "na-transformer-producer-bulk-project-staff-index-v1-topic"
  transformer-producer-bulk-project-index-v1-topic: "na-transformer-producer-bulk-project-index-v1-topic"
  save-project: "na-save-project"
  update-project: "na-update-project"
  save-household-member-topic: "na-save-household-member-topic"
  transformer-producer-household-member-index-v1-topic: "na-transformer-producer-household-member-index-v1-topic"
  save-household-topic: "na-save-household-topic"
  update-household-topic: "na-update-household-topic"
  transformer-producer-household-index-v1-topic: "na-transformer-producer-household-index-v1-topic"
  transformer-producer-service-index-v2-topic: "na-transformer-producer-service-index-v2-topic"
  save-stock-topic: "na-save-stock-topic"
  update-stock-topic: "na-update-stock-topic"
  transformer-producer-bulk-stock-index-v1-topic: "na-transformer-producer-bulk-stock-index-v1-topic"
  transformer-producer-bulk-stock-index-updated-v1-topic: "na-transformer-producer-bulk-stock-index-updated-v1-topic"
  save-facility-topic: "na-save-facility-topic"
  update-facility-topic: "na-update-facility-topic"
  save-service: "na-save-service"
  transformer-producer-service-request-index-v1-topic: "na-transformer-producer-service-request-index-v1-topic"
  save-referral-topic: "na-save-referral-topic"
  transformer-producer-referral-index-v1-topic: "na-transformer-producer-referral-index-v1-topic"
  update-referral-topic: "na-update-referral-topic"
  save-side-effect-topic: "na-save-side-effect-topic"
  update-side-effect-topic: "na-update-side-effect-topic"
  transformer-producer-side-effect-index-v1-topic: "na-transformer-producer-side-effect-index-v1-topic"
  save-pgr-request: "na-save-pgr-request"
  transformer-save-pgr-request: "na-transformer-save-pgr-request"
  update-pgr-request: "na-update-pgr-request"
  save-hfreferral-topic: "na-save-hfreferral-topic"
  update-hfreferral-topic: "na-update-hfreferral-topic"
  transformer-producer-hfreferral-index-v1-topic: "na-transformer-producer-hfreferral-index-v1-topic"
  transformer-producer-hfreferral-service-index-topic: "na-transformer-producer-hfreferral-service-index-topic"
  transformer-producer-finance-checklist-index-v1-topic: "na-transformer-producer-finance-checklist-index-v1-topic"
  transformer-producer-special-spraying-index-topic: "na-transformer-producer-special-spraying-index-topic"
  save-attendance-log: "na-save-attendance-log"
  update-attendance-log: "na-update-attendance-log"
  transformer-save-attendance-log: "na-transformer-save-attendance-log"
  transformer-save-attendance-register: "na-transformer-save-attendance-register"
  transformer-producer-extra-transformed-checklist-index-topic: "na-transformer-producer-extra-transformed-checklist-index-topic"
  update-household-member-topic: "na-update-household-member-topic"
  save-stock-reconciliation-topic: "na-save-stock-reconciliation-topic"
  update-stock-reconciliation-topic: "na-update-stock-reconciliation-topic"
  transformer-producer-stock-recon-index-v1-topic: "na-transformer-producer-stock-recon-index-v1-topic"
  health-transformer: "na-health-transformer"
  transformer-consumer-error-tracer-topic: "error-details-indexer-topic"
  transformer-producer-error-details-index-v1-topic: "na-transformed-errors-topic"
  transformer-error-skip-error-messages: "UPLOAD_ERROR_FROM_APP"
  transformer-error-skip-error-codes: "DUPLICATE_ENTITY,INDIVIDUAL_ALREADY_MEMBER_OF_HOUSEHOLD,HOUSEHOLD_ALREADY_HAS_HEAD"
  transformer-error-skip-url-contains: "facility,resource"
  state-level-tenantid: "na"
  expense-bill-create-health-topic: "na-expense-bill-create-health"
  expense-bill-update-health-topic: "na-expense-bill-update-health"
  transformer-bill-index-topic: "na-transformer-bill-index-topic"
  transformer-billdetail-index-topic: "na-transformer-billdetail-index-topic"
  expense-bill-report-save-topic: "na-expense-bill-report-save"
  expense-bill-report-update-topic: "na-expense-bill-report-update"
  transformer-billreport-index-topic: "na-transformer-billreport-index-topic"
  save-musterroll-health-topic: "na-save-musterroll-health"
  update-musterroll-health-topic: "na-update-musterroll-health"
  transformer-producer-muster-roll-index-v1-topic: "na-transformer-producer-muster-roll-index-v1-topic"
  expense-bill-detail-create-topic: "na-expense-bill-detail-create"
  expense-bill-detail-update-topic: "na-expense-bill-detail-update"
  egov_localization_locale_code: "en_NG"
  egov-localization-module-name: "hcm-boundary-admin"
  transformer-consumer-create-user-action-topic: "na-save-user-action-project-task-topic"
  transformer-consumer-update-user-action-topic: "na-update-user-action-project-task-topic"
  transformer-producer-user-action-index-v1-topic: "na-transformer-producer-user-action-index-v1-topic"

# hcm-moz-impl:
#   namespace: nasarawa
#   replicas: 1
#   heap: "-Xmx2048m -Xms2048m"
#   memory_limits: "2Gi"
#   startDate: "29/05/2025"
#   endDate: "02/06/2025"
#   boundary-code: : : "na"
#   create-boundaryCSV-data: : : "na-create-boundaryCSV-data"
#   update-dhis2-job: : : "na-update-dhis2-job"
#   create-dhis2-job: : : "na-create-dhis2-job"
#   create-boundary-data: : : "na-create-boundary-data"
#   update-digit-dhis2-mapping: : : "na-update-digit-dhis2-mapping"
#   create-digit-dhis2-mapping: : : "na-create-digit-dhis2-mapping"
#   update-digit-record: : : "na-update-digit-record"
#   create-digit-record: : : "na-create-digit-record"
#   update-dhis2-digit-mapping: : : "na-update-dhis2-digit-mapping"
#   create-dhis2-digit-mapping: : : "na-create-dhis2-digit-mapping"
#   update-dhis2-record: : : "na-update-dhis2-record"
#   create-dhis2-record: : : "na-create-dhis2-record"
#   resources:
#     requests:
#       memory: "3Gi"
#     limits:
#       memory: "3Gi"


digit-ui:
  namespace: nasarawa
  image:
    repository: egovio/digit-ui
    tag: impel-central-instance-nigeria-multiarch-new-f9b9f6fb
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfig-na.js type=text/javascript></script>
      ';"

dashboard-ui:
  namespace: nasarawa
  image:
    repository: egovio/dashboard-ui
    tag: HDDF-4931-80af5c0
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfigDashboard-na.js type=text/javascript></script>
      ';"

workbench-ui:
  namespace: nasarawa
  image:
    repository: egovio/workbench-ui
    tag: HDDF-4931-d008fbe
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfigWorkbench-na.js type=text/javascript></script>
      ';"

payments-ui:
  namespace: nasarawa
  image:
    repository: egovio/payments-ui
    tag: HDDF-4931-427abb8
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfigPayments-na.js type=text/javascript></script>
      ';"
