global:
  domain: ondo-hcm.digit.org
# egov-localization:
#   namespace: "ondo"
#   heap: "-Xmx512m -Xms512m"
#   memory_limits: "512Mi"
#   resources:
#     requests:
#       memory: "512Mi"
#     limits:
#       memory: "512Mi"


# boundary-service:
#   namespace: "ondo"
#   heap: "-Xmx512m -Xms512m"
#   memory_limits: "512Mi"
#   resources:
#     requests:
#       memory: "512Mi"
#     limits:
#       memory: "512Mi"

# egov-idgen:
#   namespace: "ondo"
#   heap: "-Xmx512m -Xms512m"
#   memory_limits: "512Mi"
#   resources:
#     requests:
#       memory: "512Mi"
#     limits:
#       memory: "512Mi"

# egov-enc-service:
#   namespace: "ondo"
#   heap: "-Xmx512m -Xms512m"
#   memory_limits: "512Mi"
#   resources:
#     requests:
#       memory: "512Mi"
#     limits:
#       memory: "512Mi"




transformer:
  replicas: 1
  namespace: "ondo"
  heap: "-Xmx1536m -Xms1536m"
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
  cpu_requests: 300m
  memory_requests: 1.75Gi
  cpu_limits: 400m
  memory_limits: 2.25Gi
  java-enable-debug: true
  save-project-task-topic: "od-save-project-task-topic"
  update-project-task-topic: "od-update-project-task-topic"
  transformer-producer-bulk-project-task-index-v1-topic: "od-transformer-producer-bulk-project-task-index-v1-topic"
  save-project-staff-topic: "od-save-project-staff-topic"
  update-project-staff-topic: "od-update-project-staff-topic"
  transformer-producer-bulk-project-staff-index-v1-topic: "od-transformer-producer-bulk-project-staff-index-v1-topic"
  transformer-producer-bulk-project-index-v1-topic: "od-transformer-producer-bulk-project-index-v1-topic"
  save-project: "od-save-project"
  update-project: "od-update-project"
  save-household-member-topic: "od-save-household-member-topic"
  transformer-producer-household-member-index-v1-topic: "od-transformer-producer-household-member-index-v1-topic"
  save-household-topic: "od-save-household-topic"
  update-household-topic: "od-update-household-topic"
  transformer-producer-household-index-v1-topic: "od-transformer-producer-household-index-v1-topic"
  transformer-producer-service-index-v2-topic: "od-transformer-producer-service-index-v2-topic"
  save-stock-topic: "od-save-stock-topic"
  update-stock-topic: "od-update-stock-topic"
  transformer-producer-bulk-stock-index-v1-topic: "od-transformer-producer-bulk-stock-index-v1-topic"
  save-facility-topic: "od-save-facility-topic"
  update-facility-topic: "od-update-facility-topic"
  save-service: "od-save-service"
  transformer-producer-service-request-index-v1-topic: "od-transformer-producer-service-request-index-v1-topic"
  save-referral-topic: "od-save-referral-topic"
  transformer-producer-referral-index-v1-topic: "od-transformer-producer-referral-index-v1-topic"
  update-referral-topic: "od-update-referral-topic"
  save-side-effect-topic: "od-save-side-effect-topic"
  update-side-effect-topic: "od-update-side-effect-topic"
  transformer-producer-side-effect-index-v1-topic: "od-transformer-producer-side-effect-index-v1-topic"
  save-pgr-request: "od-save-pgr-request"
  transformer-save-pgr-request: "od-transformer-save-pgr-request"
  update-pgr-request: "od-update-pgr-request"
  save-hfreferral-topic: "od-save-hfreferral-topic"
  update-hfreferral-topic: "od-update-hfreferral-topic"
  transformer-producer-hfreferral-index-v1-topic: "od-transformer-producer-hfreferral-index-v1-topic"
  transformer-producer-hfreferral-service-index-topic: "od-transformer-producer-hfreferral-service-index-topic"
  transformer-producer-finance-checklist-index-v1-topic: "od-transformer-producer-finance-checklist-index-v1-topic"
  transformer-producer-special-spraying-index-topic: "od-transformer-producer-special-spraying-index-topic"
  save-attendance-log: "od-save-attendance-log"
  update-attendance-log: "od-update-attendance-log"
  transformer-save-attendance-log: "od-transformer-save-attendance-log"
  transformer-save-attendance-register: "od-transformer-save-attendance-register"
  transformer-save-attendance-staff: "od-save-staff"
  transformer-update-attendance-staff: "od-update-staff"
  transformer-save-attendance-attendee: "od-save-attendee"
  transformer-update-attendance-attendee: "od-update-attendee"
  transformer-producer-attendance-staff-index: "od-transformer-producer-attendance-staff-index"
  transformer-producer-attendee-index: "od-transformer-producer-attendee-index"
  transformer-producer-error-details-index-v1-topic: "od-transformed-errors-topic"
  transformer-producer-extra-transformed-checklist-index-topic: "od-transformer-producer-extra-transformed-checklist-index-topic"
  update-household-member-topic: "od-update-household-member-topic"
  save-stock-reconciliation-topic: "od-save-stock-reconciliation-topic"
  update-stock-reconciliation-topic: "od-update-stock-reconciliation-topic"
  transformer-producer-stock-recon-index-v1-topic: "od-transformer-producer-stock-recon-index-v1-topic"
  health-transformer: "od-health-transformer"
  transformer-consumer-attendance-enabled: "false"
  transformer-consumer-attendance-staff-enabled: "false"
  transformer-consumer-attendee-enabled: "false"
  transformer-consumer-bill-enabled: "false"
  transformer-consumer-billdetail-enabled: "false"
  transformer-consumer-billreport-enabled: "false"
  transformer-consumer-musterroll-enabled: "false"
  transformer-consumer-service-enabled: "false"
  transformer-consumer-side-effect-enabled: "false"

hcm-moz-impl:
  namespace: ondo
  replicas: 1
  heap: "-Xmx2048m -Xms2048m"
  memory_limits: "2Gi"
  startDate: "21/08/2025"
  endDate: "26/08/2025"
  boundary-code: "od"
  create-boundaryCSV-data: "od-create-boundaryCSV-data"
  update-dhis2-job: "od-update-dhis2-job"
  create-dhis2-job: "od-create-dhis2-job"
  create-boundary-data: "od-create-boundary-data"
  update-digit-dhis2-mapping: "od-update-digit-dhis2-mapping"
  create-digit-dhis2-mapping: "od-create-digit-dhis2-mapping"
  update-digit-record: "od-update-digit-record"
  create-digit-record: "od-create-digit-record"
  update-dhis2-digit-mapping: "od-update-dhis2-digit-mapping"
  create-dhis2-digit-mapping: "od-create-dhis2-digit-mapping"
  update-dhis2-record: "od-update-dhis2-record"
  create-dhis2-record: "od-create-dhis2-record"
  resources:
    requests:
      memory: "3Gi"
    limits:
      memory: "3Gi"


digit-ui:
  namespace: ondo
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://central-instance-assets.s3.af-south-1.amazonaws.com/globalConfig-od.js type=text/javascript></script>
      ';"
