# Common Labels
labels:
  app: "referralmanagement"
  group: "health"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "referralmanagement" 

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "referralmanagement_schema"
    image:
      repository: "referralmanagement-db"

# Container Configs
image:
  repository: "referralmanagement"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/referralmanagement/health"
  readinessProbePath: "/referralmanagement/health"
appType: "java-spring"
downsync-services-enabled: false
heap: "-Xmx192m -Xms192m"
java-args: ""
persist-yml-path: "file:///work-dir/health-campaign-config/egov-persister/referral-management-persister.yml"
indexer-yml-path: "file:///work-dir/health-campaign-config/egov-indexer/referral-management-indexer.yml"

kafka-consumer-group-id: health-referral-management
referralmanagement-sideeffect-kafka-create-topic: save-side-effect-topic
referralmanagement-sideeffect-kafka-update-topic: update-side-effect-topic
referralmanagement-sideeffect-kafka-delete-topic: delete-side-effect-topic
referralmanagement-sideeffect-consumer-bulk-create-topic: save-side-effect-bulk-topic
referralmanagement-sideeffect-consumer-bulk-update-topic: update-side-effect-bulk-topic
referralmanagement-sideeffect-consumer-bulk-delete-topic: delete-side-effect-bulk-topic
referralmanagement-referral-kafka-create-topic: save-referral-topic
referralmanagement-referral-kafka-update-topic: update-referral-topic
referralmanagement-referral-kafka-delete-topic: delete-referral-topic
referralmanagement-referral-consumer-bulk-create-topic: save-referral-bulk-topic
referralmanagement-referral-consumer-bulk-update-topic: update-referral-bulk-topic
referralmanagement-referral-consumer-bulk-delete-topic: delete-referral-bulk-topic
referralmanagement-hfreferral-kafka-create-topic: save-hfreferral-topic
referralmanagement-hfreferral-kafka-update-topic: update-hfreferral-topic
referralmanagement-hfreferral-kafka-delete-topic: delete-hfreferral-topic
referralmanagement-hfreferral-consumer-bulk-create-topic: save-hfreferral-bulk-topic
referralmanagement-hfreferral-consumer-bulk-update-topic: update-hfreferral-bulk-topic
referralmanagement-hfreferral-consumer-bulk-delete-topic: delete-hfreferral-bulk-topic

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: {{ index .Values "kafka-consumer-group-id" | quote }}
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: REFERRALMANAGEMENT_SIDEEFFECT_IDGEN_ID_FORMAT
    value: "referralmanagement.sideeffect.id"
  - name: REFERRALMANAGEMENT_REFERRAL_IDGEN_ID_FORMAT
    value: "referralmanagement.referral.id"
  - name: SPRING_REDIS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: redis-downsync-host
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user-egov
  - name: EGOV_SEARCH_USER_URL
    value: "/user/_search"
  - name: EGOV_USER_INTEGRATION_ENABLED
    value: "true"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_LOCATION_HOST
    value: ""
  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service
  - name: EGOV_BOUNDARY_SEARCH_URL
    value: "/boundary-service/boundary/_search"
  - name: EGOV_BOUNDARY_HIERARCHY_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: boundary-hierarchy
  - name: EGOV_LOCATION_CONTEXT_PATH
    value: "/egov-location/location/v11"
  - name: EGOV_LOCATION_ENDPOINT
    value: "/boundarys/_search"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-v2
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/mdms-v2/v1/_search"
  - name: EGOV_MDMS_PATH
    value: "/mdms-v2/v1/_search"
  - name: MDMS_PATH
    value: "/mdms-v2/v1/_search"
  - name: EGOV_MDMS_INTEGRATION_ENABLED
    value: "true"
  - name: EGOV_MDMS_MASTER_NAME
    value: "referralmanagement_master"
  - name: EGOV_MDMS_MODULE_NAME
    value: "referralmanagement"
  - name: EGOV_PRODUCT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: product
  - name: EGOV_SEARCH_PRODUCT_VARIANT_URL
    value: "/product/variant/v1/_search"
  {{- if index .Values "downsync-services-enabled" }}
  - name: EGOV_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project-referral
  - name: EGOV_SEARCH_PROJECT_TASK_URL
    value: "/project-referral/task/v1/_search"
  - name: EGOV_SEARCH_PROJECT_BENEFICIARY_URL
    value: "/project-referral/beneficiary/v1/_search"
  - name: EGOV_SEARCH_PROJECT_STAFF_URL
    value: "/project-referral/staff/v1/_search"
  - name: EGOV_SEARCH_PROJECT_URL
    value: "/project-referral/v1/_search"
  - name: EGOV_SEARCH_PROJECT_FACILITY_URL
    value: "/project-referral/facility/v1/_search"
  - name: EGOV_HOUSEHOLD_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: household-referral
  - name: EGOV_SEARCH_HOUSEHOLD_URL
    value: "/household-referral/v1/_search"
  - name: EGOV_SEARCH_HOUSEHOLD_MEMBER_URL
    value: "/household-referral/member/v1/_search"
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: individual-referral
  - name: EGOV_SEARCH_INDIVIDUAL_URL
    value: "/individual-referral/v1/_search"
  {{- else }}
  - name: EGOV_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project
  - name: EGOV_SEARCH_PROJECT_TASK_URL
    value: "/project/task/v1/_search"
  - name: EGOV_SEARCH_PROJECT_BENEFICIARY_URL
    value: "/project/beneficiary/v1/_search"
  - name: EGOV_SEARCH_PROJECT_STAFF_URL
    value: "/project/staff/v1/_search"
  - name: EGOV_SEARCH_PROJECT_URL
    value: "/project/v1/_search"
  - name: EGOV_SEARCH_PROJECT_FACILITY_URL
    value: "/project/facility/v1/_search"
  - name: EGOV_HOUSEHOLD_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: household
  - name: EGOV_SEARCH_HOUSEHOLD_URL
    value: "/household/v1/_search"
  - name: EGOV_SEARCH_HOUSEHOLD_MEMBER_URL
    value: "/household/member/v1/_search"
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: individual
  - name: EGOV_SEARCH_INDIVIDUAL_URL
    value: "/individual/v1/_search"
  {{- end }}
  - name: REFERRALMANAGEMENT_SIDEEFFECT_KAFKA_CREATE_TOPIC
    value: {{ index .Values "referralmanagement-sideeffect-kafka-create-topic" | quote }}
  - name: REFERRALMANAGEMENT_SIDEEFFECT_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "referralmanagement-sideeffect-kafka-update-topic" | quote }}
  - name: REFERRALMANAGEMENT_SIDEEFFECT_KAFKA_DELETE_TOPIC
    value: {{ index .Values "referralmanagement-sideeffect-kafka-delete-topic" | quote }}
  - name: REFERRALMANAGEMENT_SIDEEFFECT_CONSUMER_BULK_CREATE_TOPIC
    value: {{ index .Values "referralmanagement-sideeffect-consumer-bulk-create-topic" | quote }}
  - name: REFERRALMANAGEMENT_SIDEEFFECT_CONSUMER_BULK_UPDATE_TOPIC
    value: {{ index .Values "referralmanagement-sideeffect-consumer-bulk-update-topic" | quote }}
  - name: REFERRALMANAGEMENT_SIDEEFFECT_CONSUMER_BULK_DELETE_TOPIC
    value: {{ index .Values "referralmanagement-sideeffect-consumer-bulk-delete-topic" | quote }}
  - name: REFERRALMANAGEMENT_REFERRAL_KAFKA_CREATE_TOPIC
    value: {{ index .Values "referralmanagement-referral-kafka-create-topic" | quote }}
  - name: REFERRALMANAGEMENT_REFERRAL_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "referralmanagement-referral-kafka-update-topic" | quote }}
  - name: REFERRALMANAGEMENT_REFERRAL_KAFKA_DELETE_TOPIC
    value: {{ index .Values "referralmanagement-referral-kafka-delete-topic" | quote }}
  - name: REFERRALMANAGEMENT_REFERRAL_CONSUMER_BULK_CREATE_TOPIC
    value: {{ index .Values "referralmanagement-referral-consumer-bulk-create-topic" | quote }}
  - name: REFERRALMANAGEMENT_REFERRAL_CONSUMER_BULK_UPDATE_TOPIC
    value: {{ index .Values "referralmanagement-referral-consumer-bulk-update-topic" | quote }}
  - name: REFERRALMANAGEMENT_REFERRAL_CONSUMER_BULK_DELETE_TOPIC
    value: {{ index .Values "referralmanagement-referral-consumer-bulk-delete-topic" | quote }}
  - name: REFERRALMANAGEMENT_HFREFERRAL_KAFKA_CREATE_TOPIC
    value: {{ index .Values "referralmanagement-hfreferral-kafka-create-topic" | quote }}
  - name: REFERRALMANAGEMENT_HFREFERRAL_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "referralmanagement-hfreferral-kafka-update-topic" | quote }}
  - name: REFERRALMANAGEMENT_HFREFERRAL_KAFKA_DELETE_TOPIC
    value: {{ index .Values "referralmanagement-hfreferral-kafka-delete-topic" | quote }}
  - name: REFERRALMANAGEMENT_HFREFERRAL_CONSUMER_BULK_CREATE_TOPIC
    value: {{ index .Values "referralmanagement-hfreferral-consumer-bulk-create-topic" | quote }}
  - name: REFERRALMANAGEMENT_HFREFERRAL_CONSUMER_BULK_UPDATE_TOPIC
    value: {{ index .Values "referralmanagement-hfreferral-consumer-bulk-update-topic" | quote }}
  - name: REFERRALMANAGEMENT_HFREFERRAL_CONSUMER_BULK_DELETE_TOPIC
    value: {{ index .Values "referralmanagement-hfreferral-consumer-bulk-delete-topic" | quote }}
  - name: SEARCH_API_LIMIT
    value: "1000"
  - name: REFERRALMANAGEMENT_DOCUMENT_ID_VERIFICATION_REQUIRED
    value: "false"
  - name: REFERRALMANAGEMENT_DEFAULT_OFFSET
    value: "0"
  - name: REFERRALMANAGEMENT_DEFAULT_LIMIT
    value: "100"
  - name: REFERRALMANAGEMENT_SEARCH_MAX_LIMIT
    value: "200"
  - name: EGOV_IDGEN_PROJECT_NUMBER_NAME
    value: "project.number"
  - name: PROJECT_RESOURCE_IDGEN_ID_FORMAT
    value: "project.resource.id"
  - name: EGOV_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: facility
  - name: EGOV_SEARCH_FACILITY_URL
    value: "/facility/v1/_search"
  - name: PROJECT_MDMS_MODULE
    value: "HCM-PROJECT-TYPES"
  - name: EGOV_LOCATION_HIERARCHY_TYPE
    value: "IRS"
  - name: EGOV_LOCATION_CODE_QUERY_PARAM
    value: "code"
  - name: EGOV_ENABLE_MATVIEW_SEARCH
    value: "true"
