apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jigawa-appset-ui
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dashboard-ui
          - name: workbench-ui
          - name: payments-ui

  template:
    metadata:
      name: 'jigawa-{{name}}'

    spec:
      project: jigawa-project

      source:
        repoURL: git@github.com:HCM-BAUCHI/Nigeria-Devops.git
        targetRevision: ng-central-prd
        path: deploy-as-code/helm/charts/frontend/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../environments/jigawa-central-prd.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: jigawa

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas