apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-nodes-and-metrics
rules:
  # View nodes
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/status
    verbs:
      - get
      - list
      - watch

  # View node & pod metrics
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
