# Common Labels
labels:
  app: "egov-hrms"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-hrms"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_hrms_schema"
    image:
      repository: "egov-hrms-db"

# Container Configs
image:
  repository: "egov-hrms"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-hrms/health"
  readinessProbePath: "/egov-hrms/health"
appType: "java-spring"
java-enable-debug: true
employee-applink: "https://egov-micro-dev.egovernments.org/employee/user/login"
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"

kafka-consumer-group-id: employee-group1
kafka-topics-save-service: save-hrms-employee
kafka-topics-update-service: update-hrms-employee
kafka-topics-notification-sms: egov.core.notification.sms
kafka-topics-notification-email: egov.core.notification.email
kafka-topics-hrms-update-data: egov-hrms-update
kafka-topics-hrms-email-notification: hrms-send-email-notification

egov-hrms-default-pagination-limit: "200"
egov-hrms-default-pwd-length: "8"
open-search-enabled-roles: "SUPERUSER"
egov-pwd-allowed-special-characters: "@#$%"
decryption-abac-enable: "false"
notification-email-enabled: "true"
parent-level-tenant-id: "pb"
egov-hrms-auto-generate-password: "false"
egov-user-create-bulk-endpoint: "/user/users/v2/_create"
egov-individual-create-bulk-endpoint: "/individual/v1/bulk/_create"
egov-hrms-mobile-number-min-length: "8"
egov-hrms-mobile-number-max-length: "11"

# Additional Container Envs
env: |
  - name: EGOV_SERVICES_DATA_SYNC_EMPLOYEE_REQUIRED 
    value:  "false"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-v2
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/mdms-v2/v1/_search"
  - name: EGOV_MDMS_PATH
    value: "/mdms-v2/v1/_search"
  - name: MDMS_PATH
    value: "/mdms-v2/v1/_search"
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id     
  - name: EGOV_FILESTORE_URL_ENDPOINT
    value: /filestore/v1/files/url
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_LOCALIZATION_SEARCH_ENDPOINT
    value: /localization/messages/v1/_search
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_SERVICES_EGOV_IDGEN_CREATEPATH
    value: /egov-idgen/id/_generate
  - name: EGOV_SERVICES_EGOV_IDGEN_EMP_CODE_NAME
    value: employee.code
  - name: EGOV_SERVICES_EGOV_IDGEN_EMP_CODE_FORMAT
    value: EMP_[SEQ_EMPLOYEE_CODE]
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_OTP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-otp 
  - name: EGOV_ENVIRONMENT_DOMAIN
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_USER_SEARCH_ENDPOINT
    value: /user/v1/_search
  - name: EGOV_USER_CREATE_ENDPOINT
    value: /user/users/_createnovalidate
  - name: EGOV_USER_UPDATE_ENDPOINT
    value: /user/users/_updatenovalidate
  - name: EGOV_HRMS_EMPLOYEE_APP_LINK
    value: {{ index .Values "employee-applink" | quote }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: {{ index .Values "kafka-consumer-group-id" | quote }}
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: KAFKA_TOPICS_SAVE_SERVICE
    value: {{ index .Values "kafka-topics-save-service" | quote }}
  - name: KAFKA_TOPICS_UPDATE_SERVICE
    value: {{ index .Values "kafka-topics-update-service" | quote }}
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: {{ index .Values "kafka-topics-notification-sms" | quote }}
  - name: KAFKA_TOPICS_NOTIFICATION_EMAIL
    value: {{ index .Values "kafka-topics-notification-email" | quote }}
  - name: KAFKA_TOPICS_HRMS_UPDATEDATA
    value: {{ index .Values "kafka-topics-hrms-update-data" | quote }}
  - name: KAFKA_TOPICS_HRMS_EMAIL_NOTIFICATION
    value: {{ index .Values "kafka-topics-hrms-email-notification" | quote }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_HRMS_AUTO_GENERATE_PASSWORD
    value: {{ index .Values "egov-hrms-auto-generate-password" | quote }}
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: individual
  - name: EGOV_INDIVIDUAL_SEARCH_ENDPOINT
    value: "/individual/v1/_search"
  - name: EGOV_INDIVIDUAL_CREATE_ENDPOINT
    value: "/individual/v1/_create"
  - name: EGOV_INDIVIDUAL_UPDATE_ENDPOINT
    value: "/individual/v1/_update"
  - name: EGOV_INDIVIDUAL_DELETE_ENDPOINT
    value: "/individual/v1/_delete"
  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service
  - name: EGOV_BOUNDARY_SEARCH_URL
    value: "/boundary-service/boundary/_search"
  - name: EGOV_BOUNDARY_HIERARCHY_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: boundary-hierarchy
  - name: EGOV_HRMS_USER_SERVICE_QUALIFIER
    value: "individualService"
  - name: MANAGEMENT_HEALTH_REDIS_ENABLED
    value: "false"
  - name: EGOV_HRMS_DEFAULT_PAGINATION_LIMIT
    value: {{ index .Values "egov-hrms-default-pagination-limit" | quote }}
  - name: EGOV_HRMS_DEFAULT_PWD_LENGTH
    value: {{ index .Values "egov-hrms-default-pwd-length" | quote }}
  - name: OPEN_SEARCH_ENABLED_ROLES
    value: {{ index .Values "open-search-enabled-roles" | quote }}
  - name: EGOV_PWD_ALLOWED_SPECIAL_CHARACTERS
    value: {{ index .Values "egov-pwd-allowed-special-characters" | quote }}
  - name: DECRYPTION_ABAC_ENABLE
    value: {{ index .Values "decryption-abac-enable" | quote }}
  - name: NOTIFICATION_EMAIL_ENABLED
    value: {{ index .Values "notification-email-enabled" | quote }}
  - name: PARENT_LEVEL_TENANT_ID
    value: {{ index .Values "parent-level-tenant-id" | quote }}
  - name: EGOV_USER_CREATE_BULK_ENDPOINT
    value: {{ index .Values "egov-user-create-bulk-endpoint" | quote }}
  - name: EGOV_INDIVIDUAL_CREATE_BULK_ENDPOINT
    value: {{ index .Values "egov-individual-create-bulk-endpoint" | quote }}
  - name: EGOV_HRMS_MOBILE_NUMBER_MIN_LENGTH
    value: {{ index .Values "egov-hrms-mobile-number-min-length" | quote }}
  - name: EGOV_HRMS_MOBILE_NUMBER_MAX_LENGTH
    value: {{ index .Values "egov-hrms-mobile-number-max-length" | quote }}

