apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ng-central-prd-egov-appset-core
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: pdf-service
          - name: service-request
          - name: egov-notification-mail
          - name: egov-notification-push
          - name: boundary-service
          - name: inbox
          - name: egov-accesscontrol
          - name: egov-enc-service
          - name: egov-filestore
          - name: egov-idgen
          - name: egov-indexer
          - name: egov-localization
          # - name: egov-persister
          # - name: egov-persister-azm
          # - name: egov-persister-chad
          # - name: egov-persister-go-ad
          # - name: egov-persister-ht
          # - name: egov-user
          - name: egov-workflow-v2
          - name: error-handler
          - name: mdms-v2
          - name: pgr-services
          - name: egov-user
          # - name: gateway
          # - name: gateway-2
          # - name: internal-gateway-scg

  template:
    metadata:
      name: 'egov-{{name}}'

    spec:
      project: egov-project

      source:
        repoURL: git@github.com:HCM-BAUCHI/Nigeria-Devops.git
        targetRevision: ng-central-prd
        path: deploy-as-code/helm/charts/core-services/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../environments/bauchi-central-prd.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: '*'

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
