apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: egov
  name: egov_access_deploy_gombe_role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch","patch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "list", "create", "watch"]  