apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kaduna-hcm-central.digit.org-tls-certs
  namespace: egov
spec:
  secretName: kaduna-hcm-central.digit.org-tls-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kaduna-hcm-central.digit.org
  dnsNames:
  - kaduna-hcm-central.digit.org

